import { Adquisicion, Carpeta, Firma, Plantilla } from "@/types";

export const FOLDER_TEMPLATES: {
  numero: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;
  nombre: string;
  tipo_generacion: "IA" | "MANUAL";
  descripcion: string;
}[] = [
  {
    numero: 1,
    nombre: "TDR (Términos de Referencia / Especificaciones)",
    tipo_generacion: "IA",
    descripcion: "Generación y visualización del documento oficial de Especificaciones Técnicas (idéntico a la plantilla institucional ENDE Deoruro).",
  },
  {
    numero: 2,
    nombre: "Form S1-N014 (Solicitud de Adquisición)",
    tipo_generacion: "MANUAL",
    descripcion: "Subida obligatoria del formulario oficial. Extracción OCR de partida y cuadro de ítems.",
  },
  {
    numero: 3,
    nombre: "Cuadro de Justificación",
    tipo_generacion: "MANUAL",
    descripcion: "Subida y procesamiento de justificación técnica y criterio de evaluación (Art. 31).",
  },
  {
    numero: 4,
    nombre: "Solicitud de Cotización a Empresas",
    tipo_generacion: "MANUAL",
    descripcion: "Almacenamiento de proformas de proveedores con verificación de NIT.",
  },
  {
    numero: 5,
    nombre: "Solicitud de Inicio de Proceso",
    tipo_generacion: "IA",
    descripcion: "Generación de la Solicitud de Inicio de Proceso de Compra oficial.",
  },
  {
    numero: 6,
    nombre: "Form S2-N014 (Solicitud de Cotización)",
    tipo_generacion: "IA",
    descripcion: "Generación con IA del pliego oficial de invitación a cotizar.",
  },
  {
    numero: 7,
    nombre: "Informe de Conformidad",
    tipo_generacion: "MANUAL",
    descripcion: "Recepción técnica y conformidad de entrega (validación de concordancia de objeto).",
  },
  {
    numero: 8,
    nombre: "Documento Final / Contrato / Orden",
    tipo_generacion: "MANUAL",
    descripcion: "Cierre formal del expediente y archivo definitivo.",
  },
];

export function createInitialFolders(adquisicionId: string): Carpeta[] {
  return FOLDER_TEMPLATES.map((tmpl) => ({
    id: `carpeta-${adquisicionId}-${tmpl.numero}`,
    adquisicion_id: adquisicionId,
    numero: tmpl.numero,
    nombre: tmpl.nombre,
    tipo_generacion: tmpl.tipo_generacion,
    estado: tmpl.numero === 1 ? "Completado" : "Pendiente",
    descripcion: tmpl.descripcion,
    documentos: [],
  }));
}

export const INITIAL_ADQUISICIONES: Adquisicion[] = [
  {
    id: "acq-1",
    codigo: "ENDE-D-2026-001",
    titulo_proceso: "ADQUISICIÓN DE HERRAMIENTA PARA CUADRILLAS",
    categoria: "Bienes",
    modalidad: "Menor Precio (Art. 31 Reglamento SBC)",
    partida_presupuestaria: "39500 - Herramientas Menores",
    estado: "Iniciado",
    prevision_presupuesto: 145000.0,
    moneda: "BOB",
    fecha_inicio: "2026-05-15",
    fecha_limite: "2026-08-15",
    unidad_solicitante: "Departamento Técnico de Mantenimiento de Redes Eléctricas",
    responsable_proceso: "Ing. Heydi Canaviri Padilla - Supervisora Seguridad Industrial",
    creado_por: "admin@ende-deoruro.bo",
    fecha_creacion: "2026-05-10T08:30:00Z",
    fecha_actualizacion: "2026-05-15T10:15:00Z",
    plazo_entrega_dias: 120,
    multa_diaria_porcentaje: 0.25,
    lugar_entrega: "Almacenes ENDE DEORURO S.A., Oruro - Bolivia",

    // Datos oficiales de la Plantilla Institucional ENDE Deoruro (PDF)
    revision: "Rev. N° 1",
    mes_anio_documento: "Mayo - 2026",
    elaborado_por: "Heydi Canaviri Padilla",
    elaborado_cargo: "Supervisora Seguridad Industrial",
    revisado_por: "Heydi Canaviri Padilla",
    revisado_cargo: "Supervisora Seguridad Industrial",
    aprobado_por: "Lic. Raul Alberto Torrico Gomez",
    aprobado_cargo: "Gerencia ENDE Deoruro S.A.",

    antecedentes_texto: "De acuerdo a la legislación vigente, normas y políticas internas se inicia el proceso de adquisición de herramientas y equipos para mantenimiento redes MT, enmarcados en el manual de procedimientos y Reglamento de Adquisición de Bienes, Construcción de Obras y Contratación de Servicios.",
    justificacion_texto: "Con la adquisición de herramientas de zapa para mantenimiento redes MT, tiene el objetivo de prevenir accidentes que pueden ser producto del uso de herramientas de zapa en mal estado también o a la ausencia de estas herramientas.",
    calidad_texto: "El ofertante deberá presentar un certificado en el cual garantice que las herramientas cumplan con todas las características técnicas y los estándares de calidad de acuerdo a normativa vigente.",
    metodo_seleccion_texto: "Menor Precio (Art. 31 Reglamento SBC)",
    vigencia_propuesta_texto: "Mínimo 30 días calendario computables a partir de la apertura de propuestas.",
    forma_pago_texto: "El pago se realizará contra entrega satisfactoria del producto, conformidad de la Distribuidora de Electricidad ENDE DEORURO S.A. y entrega de la siguiente documentación: Nota de Entrega, Solicitud de Pago y Factura.",

    items: [
      {
        id: "item-1",
        item: 1,
        codigoArticulo: "HERR-001",
        descripcion: "Tijera Corta Cable de Acero",
        unidad: "PZA",
        cantidad: 4,
        precioUnitarioEstimado: 3800,
        precioTotalEstimado: 15200,
        fichaTecnica: {
          uso: "Personal Operativo",
          normaCertificacion: "Norma ASTM A36 / ISO 9001",
          material: "Acero al silicio manganeso 2X",
          color: "Acero pavonado con mango ergonómico antideslizante",
          aceptacionLote: "El personal de ENDE DEORURO, realizara una evaluación preliminar el día de la entrega, en caso de existir observaciones.",
          categoriaItem: "Herramientas manuales de corte",
          dimensiones: "Largo total: 36 pulgadas (90 cm)",
          capacidadCorte: "Materiales suaves: 9/16 pulg (14 mm) | Materiales duros: 7/16 pulg (11 mm) | Zona de corte: 1 1/2 pulg (38 mm)",
          pesoAprox: "5 a 7 kg",
          caracteristicasDetalle: [
            "Cuchillas de acero al silicio manganeso 2X de alta tenacidad",
            "Mango de acero tubular con grip ergonómico antiderrapante",
            "Mayor palanca para reducir el esfuerzo operativo del liniero",
            "Tornillo excéntrico regulable para un ajuste milimétrico de cuchillas"
          ]
        }
      },
      {
        id: "item-2",
        item: 2,
        codigoArticulo: "COD-63800",
        descripcion: "Tijera Corta Cable ACSR - COD-63800 (TUERA)",
        unidad: "PZA",
        cantidad: 1,
        precioUnitarioEstimado: 6500,
        precioTotalEstimado: 6500,
        fichaTecnica: {
          uso: "Personal Operativo",
          normaCertificacion: "Norma IEEE 1654 / ASTM B232",
          material: "Acero forjado de alta resistencia y vinilo aislante",
          color: "Acabado pavonado con aislamiento bicolor de alta visibilidad",
          aceptacionLote: "El personal de ENDE DEORURO, realizara una evaluación preliminar el día de la entrega, en caso de existir observaciones.",
          categoriaItem: "Herramientas manuales especializadas",
          dimensiones: "Longitud compacta de 14 pulgadas (35.6 cm) para fácil transporte en morral de liniero",
          capacidadCorte: "Corta hasta 477 MCM ACSR multi-hebra | Capacidad: 477 MCM ACSR; 1-1/4 pulgadas (32 mm) Ø CU-AL trenzado",
          pesoAprox: "2.5 kg",
          caracteristicasDetalle: [
            "Corte limpio de conductores ACSR hasta calibre 477 MCM multi-hebra",
            "Insertos de corte reemplazables con 3 tornillos de sujeción por hoja",
            "Mecanismo de trinquete de alto apalancamiento progresivo",
            "Bloqueo de seguridad integrado para transporte en bolsa de herramientas",
            "Asas con empuñaduras de vinilo con protectores de mano para agarre firme"
          ]
        }
      },
      {
        id: "item-3",
        item: 3,
        codigoArticulo: "MORD-140",
        descripcion: "Mordaza 1-4/0 AWG K",
        unidad: "PZA",
        cantidad: 3,
        precioUnitarioEstimado: 2900,
        precioTotalEstimado: 8700,
        fichaTecnica: {
          uso: "Personal Operativo",
          normaCertificacion: "Norma ASTM B230 / ASTM B231",
          material: "Acero forjado galvanizado",
          color: "Acabado galvanizado industrial anticorrosivo",
          aceptacionLote: "El personal de ENDE DEORURO, realizara una evaluación preliminar el día de la entrega, en caso de existir observaciones.",
          categoriaItem: "Herramientas de tracción y tendido",
          dimensiones: "Para cable desnudo macizo y trenzado de 0.08 pulg (2 mm) a 0.20 pulg (5.1 mm)",
          capacidadCorte: "Mordazas con ranura en V paralela antideslizante",
          pesoAprox: "1.8 kg",
          caracteristicasDetalle: [
            "Para cable desnudo macizo y trenzado de 0.08 pulg (2 mm) a 0.20 pulg (5.1 mm)",
            "Tensor liviano y de alto agarre para líneas de media y baja tensión",
            "Mordazas con ranura en V simple que impiden el deslizamiento del conductor",
            "Compatible con conductores de cobre y aluminio desnudo n.º 6 y n.º 8 sin deformación"
          ]
        }
      },
      {
        id: "item-4",
        item: 4,
        codigoArticulo: "TECLE-2TN",
        descripcion: "Tecle de Cable 2 Toneladas",
        unidad: "PZA",
        cantidad: 2,
        precioUnitarioEstimado: 7800,
        precioTotalEstimado: 15600,
        fichaTecnica: {
          uso: "Personal Operativo",
          normaCertificacion: "Norma ANSI / ASME B30.21",
          material: "Aleación de acero forjado y cable de acero galvanizado",
          color: "Esmalte industrial amarillo seguridad",
          aceptacionLote: "El personal de ENDE DEORURO, realizara una evaluación preliminar el día de la entrega, en caso de existir observaciones.",
          categoriaItem: "Equipos de izaje y tracción",
          dimensiones: "Elevación estándar: 1.5 m | Ramales: 1 | Longitud de cable: 5 m",
          capacidadCorte: "Capacidad de tiro / carga: 2 Toneladas (2000 kg)",
          pesoAprox: "6.2 kg",
          caracteristicasDetalle: [
            "Capacidad nominal de carga: 2 Toneladas métricas (2000 kg)",
            "Elevación estándar de 1.5 metros con palanca de suave accionamiento",
            "Esfuerzo necesario para levantar carga máxima: 320 N",
            "Cable de acero galvanizado de alta resistencia de 10 mm de diámetro",
            "Ganchos de acero forjado con trinquete de seguridad giratorios en 360°"
          ]
        }
      },
      {
        id: "item-5",
        item: 5,
        codigoArticulo: "TECLE-750KG",
        descripcion: "Tecle de Cadena de 750 Kg",
        unidad: "PZA",
        cantidad: 4,
        precioUnitarioEstimado: 4500,
        precioTotalEstimado: 18000,
        fichaTecnica: {
          uso: "Personal Operativo",
          normaCertificacion: "Norma ANSI / ASME B30.16 - HST-2",
          material: "Carcasa de acero estampado y cadena de eslabones Grado 80",
          color: "Esmaltado anticorrosivo amarillo de seguridad industrial",
          aceptacionLote: "El personal de ENDE DEORURO, realizara una evaluación preliminar el día de la entrega, en caso de existir observaciones.",
          categoriaItem: "Equipos de izaje y maniobra",
          dimensiones: "Izaje estándar: 1.5 m | Longitud de cadena de carga: 1.8 m",
          capacidadCorte: "Capacidad de carga: 750 kg",
          pesoAprox: "6.8 kg",
          caracteristicasDetalle: [
            "Capacidad nominal de carga: 750 kg",
            "Cadena de carga de aleación de acero Grado 80 de alta tenacidad",
            "Sistema de freno mecánico automático libre de asbesto",
            "Manivela de accionamiento con rotación continua de 360 grados",
            "Ganchos con indicadores de deformación lenta en prevención de sobrecargas",
            "Carcasa sellada para protección contra polvo e intemperie en faenas de campo"
          ]
        }
      }
    ],
  },
  {
    id: "acq-2",
    codigo: "ENDE-D-2026-002",
    titulo_proceso: "Servicio de Limpieza Industrial de Subestaciones",
    categoria: "Servicios",
    modalidad: "Menor Precio (Art. 31)",
    partida_presupuestaria: "25800 - Servicios de Aseo y Limpieza",
    estado: "Generación IA",
    prevision_presupuesto: 85500.0,
    moneda: "BOB",
    fecha_inicio: "2024-03-12",
    fecha_limite: "2024-04-30",
    unidad_solicitante: "Subestaciones y Transformación",
    responsable_proceso: "Ing. Paola Miranda - Supervisora de Operaciones",
    creado_por: "pmiranda@ende-deoruro.bo",
    fecha_creacion: "2024-03-12T09:00:00Z",
    fecha_actualizacion: "2024-03-14T15:00:00Z",
    plazo_entrega_dias: 60,
    multa_diaria_porcentaje: 0.25,
    lugar_entrega: "Subestaciones Oruro, Challapata y Poopó",
    items: [
      {
        id: "item-2-1",
        item: 1,
        descripcion: "Servicio de Desbroce y Limpieza Técnica en Playa de Transformadores",
        unidad: "Servicio Global",
        cantidad: 1,
        precioUnitarioEstimado: 85500,
        precioTotalEstimado: 85500,
      },
    ],
  },
];

export const INITIAL_PLANTILLAS: Plantilla[] = [
  {
    id: "plan-1",
    fk_carpeta: 1,
    nombre: "TDR - Especificaciones Técnicas (7 Páginas)",
    version: "2.6 (2026)",
    descripcion: "Formato institucional idéntico al PDF oficial ENDE Deoruro: Portada institucional con firmas y resumen, cabecera de 3 celdas, índice de contenidos, fichas técnicas con características de materiales y cláusulas finales.",
    fecha_creacion: "2026-01-15",
    secciones: [
      {
        id: "sec-1-1",
        tipo: "PORTADA_COVER",
        titulo: "Página 1: Portada Oficial y Resumen Ejecutivo",
        subtitulo: "Membrete ENDE Deoruro, Tabla de Control de Cambios y Bloque de 3 Firmas",
        activo: true,
        orden: 1,
        descripcion: "Portada institucional con logo, código correlativo, fecha, cuadro de revisión y cuadro resumen con firmas (Elaborado, Revisado, Aprobado).",
      },
      {
        id: "sec-1-2",
        tipo: "INDICE_LIST",
        titulo: "Página 2: Índice General y Resumen de Ítems",
        subtitulo: "Estructura de Secciones (1 al 13) y Tabla Resumen de Ítems",
        activo: true,
        orden: 2,
        descripcion: "Índice formal numerado de contenidos y cuadro resumen preliminar con cantidades y unidades de herramientas.",
      },
      {
        id: "sec-1-3",
        tipo: "FICHA_PRODUCT",
        titulo: "Páginas 3 a 6: Antecedentes, Justificación y Fichas Técnicas",
        subtitulo: "Fichas individuales por ítem con normas ASTM/ISO, materiales, color y dimensiones",
        activo: true,
        orden: 3,
        descripcion: "Redacción formal de antecedentes, justificación de la necesidad y fichas técnicas detalladas por herramienta con fotografías/gráficos.",
      },
      {
        id: "sec-1-4",
        tipo: "CLAUSULAS_LEGALES",
        titulo: "Página 7: Cláusulas Finales de Adquisición",
        subtitulo: "Calidad, Método de Selección, Vigencia, Multas, Plazo y Forma de Pago",
        activo: true,
        orden: 4,
        descripcion: "Cláusulas institucionales obligatorias según el Reglamento de Adquisiciones de ENDE Deoruro S.A.",
      },
    ],
    firmantes_default: [
      {
        id: "firm-1-1",
        rol: "ELABORADO",
        etiqueta: "Elaborado por",
        nombreDefault: "Heydi Canaviri Padilla",
        cargoDefault: "Supervisora Seguridad Industrial",
      },
      {
        id: "firm-1-2",
        rol: "REVISADO",
        etiqueta: "Revisado por",
        nombreDefault: "Heydi Canaviri Padilla",
        cargoDefault: "Supervisora Seguridad Industrial",
      },
      {
        id: "firm-1-3",
        rol: "APROBADO",
        etiqueta: "Aprobado por",
        nombreDefault: "Lic. Raul Alberto Torrico Gomez",
        cargoDefault: "Gerencia ENDE Deoruro S.A.",
      },
    ],
    clausulas_default: [
      {
        id: "claus-1",
        numero: 1,
        titulo: "Garantía y Control de Calidad",
        contenido: "El ofertante deberá presentar un certificado en el cual garantice que los bienes o herramientas cumplan con todas las características técnicas y los estándares de calidad de acuerdo a normativa vigente.",
        activo: true,
      },
      {
        id: "claus-2",
        numero: 2,
        titulo: "Plazo de Entrega y Multas por Retraso",
        contenido: "El plazo máximo de entrega será de 120 días calendario. Se aplicará una multa del 0.25% por cada día de retraso injustificado en la entrega de los bienes.",
        activo: true,
      },
      {
        id: "claus-3",
        numero: 3,
        titulo: "Lugar de Entrega y Recepción",
        contenido: "La entrega de los bienes se realizará en Almacén Central de ENDE DEORURO S.A., ubicado en la ciudad de Oruro - Bolivia.",
        activo: true,
      },
      {
        id: "claus-4",
        numero: 4,
        titulo: "Forma y Condiciones de Pago",
        contenido: "El pago se realizará contra entrega satisfactoria del producto, previa emisión del Informe de Conformidad técnica y recepción formal.",
        activo: true,
      },
    ],
  },
  {
    id: "plan-2",
    fk_carpeta: 2,
    nombre: "Formulario S1-N014 - Solicitud de Adquisición",
    version: "1.8",
    descripcion: "Plantilla oficial de solicitud presupuestaria con partida de gasto y firma de unidad solicitante.",
    fecha_creacion: "2026-01-15",
    secciones: [
      {
        id: "sec-2-1",
        tipo: "FORMULARIO_NOTA",
        titulo: "Cabecera Presupuestaria y Solicitante",
        subtitulo: "Datos del Proceso y Unidad Solicitante",
        activo: true,
        orden: 1,
        descripcion: "Código correlativo, fecha de solicitud, unidad técnica y responsable.",
      },
      {
        id: "sec-2-2",
        tipo: "TABLA_PRECIOS",
        titulo: "Cuadro de Partida Presupuestaria y Montos",
        subtitulo: "Partida de Gasto (ej. 39500) y Previsión en Bolivianos",
        activo: true,
        orden: 2,
        descripcion: "Asignación de fondos y certificación de disponibilidad presupuestaria.",
      },
    ],
    firmantes_default: [
      {
        id: "firm-2-1",
        rol: "ELABORADO",
        etiqueta: "Solicitado por",
        nombreDefault: "Ing. Heydi Canaviri Padilla",
        cargoDefault: "Supervisora Seguridad Industrial",
      },
    ],
  },
  {
    id: "plan-3",
    fk_carpeta: 3,
    nombre: "Cuadro de Justificación Técnica (Art. 31 SBC)",
    version: "1.4",
    descripcion: "Matriz comparativa y exposición de necesidad del suministro según reglamento de adquisiciones.",
    fecha_creacion: "2026-01-15",
    secciones: [
      {
        id: "sec-3-1",
        tipo: "FORMULARIO_NOTA",
        titulo: "Exposición de Motivos Técnicos",
        subtitulo: "Justificación Operativa y de Seguridad Industrial",
        activo: true,
        orden: 1,
        descripcion: "Fundamentación de reposición por desgaste o ampliación de cobertura en redes eléctricas.",
      },
    ],
  },
  {
    id: "plan-4",
    fk_carpeta: 4,
    nombre: "Pliego de Cotización a Empresas con Verificación NIT",
    version: "1.2",
    descripcion: "Ficha de control de cotizaciones recibidas y habilitación de proveedores por NIT.",
    fecha_creacion: "2026-01-15",
    secciones: [
      {
        id: "sec-4-1",
        tipo: "TABLA_PRECIOS",
        titulo: "Cuadro Comparativo de Proponentes",
        subtitulo: "Precios ofertados, validez y estado tributario NIT",
        activo: true,
        orden: 1,
        descripcion: "Matriz comparativa de ofertas económicas recibidas de empresas del rubro.",
      },
    ],
  },
  {
    id: "plan-5",
    fk_carpeta: 5,
    nombre: "Solicitud de Inicio de Proceso de Compra",
    version: "2.1 (2026)",
    descripcion: "Nota oficial institucional generada para autorización gerencial e inicio del proceso de contratación con espacio para sello físico.",
    fecha_creacion: "2026-01-15",
    secciones: [
      {
        id: "sec-5-1",
        tipo: "FORMULARIO_NOTA",
        titulo: "Encabezado y Autoridades de Trámite",
        subtitulo: "No. de Nota, Fecha, A, VÍA, DE y OBJETO en mayúsculas",
        activo: true,
        orden: 1,
        descripcion: "Estructura formal de correspondencia interna institucional de ENDE Deoruro.",
      },
      {
        id: "sec-5-2",
        tipo: "CLAUSULAS_LEGALES",
        titulo: "Cuerpo de la Solicitud y Documentos de Respaldo",
        subtitulo: "Párrafos normativos en cumplimiento al Reglamento SBC",
        activo: true,
        orden: 2,
        descripcion: "Redacción formal de solicitud de inicio y mención de documentos adjuntos.",
      },
      {
        id: "sec-5-3",
        tipo: "FIRMAS_SELLOS",
        titulo: "Pie de Firma y Espacio para Sello",
        subtitulo: "Firma del solicitante y espacio reservado para sello de recepción",
        activo: true,
        orden: 3,
        descripcion: "Área de firma y sellos de aprobación de Gerencia y Contrataciones.",
      },
    ],
    firmantes_default: [
      {
        id: "firm-5-1",
        rol: "A",
        etiqueta: "Dirigido A",
        nombreDefault: "Lic. Vicente Paul Vega Ramirez",
        cargoDefault: "RESPONSABLE DE CONTRATACIONES",
      },
      {
        id: "firm-5-2",
        rol: "VIA",
        etiqueta: "VÍA",
        nombreDefault: "Lic. Raúl Alberto Torrico Gomez",
        cargoDefault: "GERENTE GENERAL",
      },
      {
        id: "firm-5-3",
        rol: "DE",
        etiqueta: "DE",
        nombreDefault: "Ing. Heydi Dunya Canaviri Padilla",
        cargoDefault: "SUPERVISOR DE SEGURIDAD INDUSTRIAL",
      },
    ],
  },
  {
    id: "plan-6",
    fk_carpeta: 6,
    nombre: "Formulario S2-N014 - Solicitud de Cotización a Proveedores",
    version: "2.1 (2026)",
    descripcion: "Invitación formal a proponentes con especificaciones técnicas y tabla de cotización para llenado de precios y sellos.",
    fecha_creacion: "2026-01-15",
    secciones: [
      {
        id: "sec-6-1",
        tipo: "FORMULARIO_NOTA",
        titulo: "Membrete Institucional y Datos de la Invitación",
        subtitulo: "Código del Proceso, Fecha Límite y Razón Social de Empresa",
        activo: true,
        orden: 1,
        descripcion: "Cabecera oficial del Formulario S2-N014 con datos de la empresa cotizante.",
      },
      {
        id: "sec-6-2",
        tipo: "TABLA_PRECIOS",
        titulo: "Tabla Oficial de Cotización (Precios en Blanco)",
        subtitulo: "Ítems, Unidades, Cantidades y Casillas para Precio Unitario y Total",
        activo: true,
        orden: 2,
        descripcion: "Tabla estructurada para que el proveedor coloque su propuesta económica y marca ofertada.",
      },
      {
        id: "sec-6-3",
        tipo: "CLAUSULAS_LEGALES",
        titulo: "Condiciones de Validez, Plazo y Observación Legal",
        subtitulo: "Vigencia de oferta mínima 30 días, NIT activo y entrega Almacén Central",
        activo: true,
        orden: 3,
        descripcion: "Cláusulas de cumplimiento tributario y condiciones obligatorias de adjudicación.",
      },
      {
        id: "sec-6-4",
        tipo: "FIRMAS_SELLOS",
        titulo: "Pie de Firma del Proponente y Sello de Empresa",
        subtitulo: "Espacio para firma del Representante Legal y Sello de la Empresa Cotizante",
        activo: true,
        orden: 4,
        descripcion: "Espacio reglamentario para firma y sello de la empresa proveedora.",
      },
    ],
    firmantes_default: [
      {
        id: "firm-6-1",
        rol: "DE",
        etiqueta: "Emitido por",
        nombreDefault: "Lic. Vicente Paul Vega Ramirez",
        cargoDefault: "Responsable de Contrataciones",
      },
    ],
  },
  {
    id: "plan-7",
    fk_carpeta: 7,
    nombre: "Informe de Conformidad y Recepción Técnica",
    version: "1.5",
    descripcion: "Certificado de cumplimiento de entrega e ingreso de almacén sin observaciones.",
    fecha_creacion: "2026-01-15",
    secciones: [
      {
        id: "sec-7-1",
        tipo: "FORMULARIO_NOTA",
        titulo: "Acta de Recepción y Verificación Técnica",
        subtitulo: "Constatación de calidad y normas de herramientas recibidas",
        activo: true,
        orden: 1,
        descripcion: "Validación de entrega de herramientas en perfecto estado y conforme a ficha técnica.",
      },
    ],
  },
  {
    id: "plan-8",
    fk_carpeta: 8,
    nombre: "Orden de Compra / Contrato Administrativo",
    version: "1.9",
    descripcion: "Documento legal de adjudicación y formalización contractual de la adquisición.",
    fecha_creacion: "2026-01-15",
    secciones: [
      {
        id: "sec-8-1",
        tipo: "CLAUSULAS_LEGALES",
        titulo: "Condiciones Contractuales y Adjudicación Definitiva",
        subtitulo: "Monto total adjudicado, garantías y firma de Gerencia General",
        activo: true,
        orden: 1,
        descripcion: "Formalización contractual del proceso de adquisición para cierre del expediente.",
      },
    ],
  },
];
