'use client';
import { useEffect, useState } from 'react';
import type { Adquisicion } from '@/types';
import { DataStore } from '@/lib/store/dataStore';
import { evaluateQuotes, EvaluationRow, initialSelection, methodLabels, Quote, QuoteEvaluation, SelectionPlan } from '@/lib/procurement/selection';

const input='w-full rounded-lg border border-slate-300 bg-white p-2 text-sm';
const button='rounded-lg border border-slate-300 bg-white hover:bg-slate-100 text-slate-800 shadow-sm px-4 py-2 text-sm font-semibold disabled:opacity-50 transition-colors cursor-pointer';
export function QuoteEvaluationPanel({adquisicion,onSaved}:{adquisicion:Adquisicion;onSaved:()=>void}) {
  const recoveryKey=`quote-draft:${adquisicion.id}`;
  const [recovery]=useState(()=>{try{const saved=JSON.parse(localStorage.getItem(recoveryKey)||'null');return saved?.updatedAt>(Date.parse(adquisicion.quote_evaluation?.updatedAt||'')||0)?saved:null;}catch{return null;}});
  const [plan,setPlan]=useState<SelectionPlan>(()=>recovery?.plan||adquisicion.quote_evaluation?.plan||adquisicion.selection_plan||{...initialSelection(adquisicion),confirmedAt:new Date().toISOString()});
  const [quotes,setQuotes]=useState<Quote[]>(()=>recovery?.quotes||adquisicion.quote_evaluation?.quotes||[]);
  const [history,setHistory]=useState<QuoteEvaluation[]>(()=>recovery?.history||adquisicion.quote_evaluation_history||[]);
  const [groupId,setGroupId]=useState(plan?.groups[0]?.id||''),[context,setContext]=useState(''),[files,setFiles]=useState<File[]>([]);
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(recovery?'Se recuperaron tus ofertas sin guardar.':''),[dirty,setDirty]=useState(!!recovery);
  useEffect(()=>{if(dirty&&plan)try{localStorage.setItem(recoveryKey,JSON.stringify({plan,quotes,history,updatedAt:Date.now()}));}catch{setError('No se pudo guardar la recuperación local. Guarda la comparación antes de salir.');}},[plan,quotes,history,dirty,recoveryKey]);
  const activePlan=plan;
  let rows:EvaluationRow[]=[],calculationError='';try{rows=evaluateQuotes(plan,quotes);}catch(e){calculationError=e instanceof Error?e.message:'Revisa las reglas.';}
  function update(id:string,patch:Partial<Quote>){setQuotes(qs=>qs.map(q=>q.id===id?{...q,reviewed:false,...patch}:q));setDirty(true);setMessage('Cambios sin guardar.');}
  async function request(action:string){const form=new FormData();form.append('request',JSON.stringify({action,plan:activePlan,groupId,context,quotes,title:adquisicion.titulo_proceso}));if(action==='read')files.forEach(f=>form.append('attachments',f));const res=await fetch('/api/evaluation',{method:'POST',body:form});if(!res.ok){const data=await res.json();throw Error(data.error||'No se pudo completar la evaluación.');}return res;}
  async function read(){setBusy(true);setError('');try{const {quote}=await (await request('read')).json();setQuotes(q=>[...q,quote]);setFiles([]);setContext('');setDirty(true);setMessage('Cotización incorporada. Revisa los datos y la evidencia antes de confirmar.');}catch(e){setError(e instanceof Error?e.message:'No se pudo leer.');}finally{setBusy(false);}}
  async function save(){setBusy(true);setError('');try{await request('calculate');const result=await DataStore.updateAdquisicion(adquisicion.id,{quote_evaluation:{plan:activePlan,quotes,updatedAt:new Date().toISOString()},quote_evaluation_history:history});if(!result.success)throw Error(result.error);const sync=await DataStore.flushPending();setDirty(false);localStorage.removeItem(recoveryKey);setMessage(sync.success?'Comparación guardada en el expediente.':'Guardada en este equipo; falta sincronizar con la nube.');onSaved();}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.');}finally{setBusy(false);}}
  async function download(){setBusy(true);setError('');try{const blob=await (await request('export')).blob();const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${adquisicion.codigo}_comparativo.docx`;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}catch(e){setError(e instanceof Error?e.message:'No se pudo descargar.');}finally{setBusy(false);}}
  return <section className="mb-5 rounded-xl border border-blue-200 bg-blue-50/40 p-4 space-y-4">
    <div><h2 className="font-bold text-lg text-primary">Comparar cotizaciones</h2><p className="text-sm">{methodLabels[plan.method]} · Reglas del TDR {plan.confirmedAt ? `confirmadas el ${new Date(plan.confirmedAt).toLocaleDateString('es-BO')}` : 'aplicadas'}. {dirty?'Cambios sin guardar.':''}</p><p className="text-sm text-slate-600">La IA lee las ofertas. Tú verificas la evidencia; la aplicación calcula los resultados.</p></div>
    <fieldset disabled={busy} className="space-y-4 min-w-0">
      {adquisicion.selection_plan&&adquisicion.selection_plan.revision!==plan.revision&&<div className="rounded-lg bg-amber-50 p-3 text-sm"><p>El TDR tiene condiciones nuevas. Esta comparación conserva las reglas anteriores.</p><button className={`${button} mt-2`} onClick={()=>{setHistory(h=>[...h,{plan:activePlan,quotes,updatedAt:new Date().toISOString()}]);setPlan(adquisicion.selection_plan!);setQuotes([]);setGroupId(adquisicion.selection_plan!.groups[0]?.id||'');setDirty(true);setMessage('Nueva comparación sin guardar. La anterior se conserva en el historial.');}}>Crear nueva comparación con las reglas actuales</button></div>}
      <details className="rounded-lg border bg-white p-3" open={!quotes.length}><summary className="font-semibold text-sm cursor-pointer">Añadir cotización de un proveedor</summary><div className="space-y-3 mt-3"><label className="block text-sm">Unidad que cotiza<select className={input} value={groupId} onChange={e=>setGroupId(e.target.value)}>{plan.groups.map(g=><option key={g.id} value={g.id}>{g.label}</option>)}</select></label><label className="block text-sm">Archivos de la cotización<input type="file" multiple accept=".pdf,.docx,.txt,.jpg,.jpeg,.png,.webp" className={input} onChange={e=>setFiles(Array.from(e.target.files||[]))}/><span className="text-slate-600">Hasta tres archivos del mismo proveedor, 3 MB en total. Incluye oferta y respaldo técnico.</span></label><label className="block text-sm">Texto o aclaraciones<textarea className={input} rows={3} value={context} onChange={e=>setContext(e.target.value)}/></label><div className="flex gap-2 flex-wrap"><button className={`${button} bg-primary text-white`} onClick={read}>Leer cotización con IA</button><button className={button} onClick={()=>{setQuotes(q=>[...q,{id:crypto.randomUUID(),provider:'',groupId,price:'',source:'Datos registrados por el evaluador',reviewed:false,minimums:{},levels:{},evidence:{}}]);setDirty(true);}}>Introducir una oferta</button></div></div></details>
      {quotes.map((quote,i)=><details key={quote.id} open={!quote.reviewed} className="rounded-lg border bg-white p-3"><summary className="font-semibold text-sm cursor-pointer">{quote.provider||`Oferta ${i+1}`} · {quote.reviewed?'Datos confirmados':'Revisar datos'}</summary><div className="mt-3 space-y-3"><div className="grid sm:grid-cols-2 gap-3"><label className="text-sm">Proveedor<input className={input} value={quote.provider} onChange={e=>update(quote.id,{provider:e.target.value})}/></label><label className="text-sm">Precio total en Bs, con el mismo alcance e impuestos<input className={input} inputMode="decimal" value={quote.price} onChange={e=>update(quote.id,{price:e.target.value})}/></label></div><label className="block text-sm">Unidad de adjudicación<select className={input} value={quote.groupId} onChange={e=>update(quote.id,{groupId:e.target.value,minimums:{},levels:{},evidence:{}})}>{plan.groups.map(g=><option key={g.id} value={g.id}>{g.label}</option>)}</select></label><p className="text-xs text-slate-600">Fuente: {quote.source}</p><label className="block text-sm">Evidencia del precio, moneda y alcance<textarea className={input} rows={2} value={quote.evidence.precio||''} onChange={e=>update(quote.id,{evidence:{...quote.evidence,precio:e.target.value}})}/></label>
      {plan.minimums.map(m=><div key={m.id} className="border-t pt-3"><label className="block text-sm font-semibold">{m.label}<select className={input} value={quote.minimums[m.id]||'unknown'} onChange={e=>update(quote.id,{minimums:{...quote.minimums,[m.id]:e.target.value as 'yes'|'no'|'unknown'}})}><option value="unknown">Por verificar</option><option value="yes">Cumple</option><option value="no">No cumple</option></select></label><label className="block text-sm">Evidencia y página<textarea className={input} rows={2} value={quote.evidence[m.id]||''} onChange={e=>update(quote.id,{evidence:{...quote.evidence,[m.id]:e.target.value}})}/></label></div>)}
      {plan.method==='calidad_precio'&&plan.criteria.map(c=><div key={c.id} className="border-t pt-3"><label className="block text-sm font-semibold">{c.label} · {c.weight} %<select className={input} value={quote.levels[c.id]||''} onChange={e=>update(quote.id,{levels:{...quote.levels,[c.id]:e.target.value}})}><option value="">Por verificar</option>{c.levels.map(l=><option key={l.id} value={l.id}>{l.label} — {l.score} puntos</option>)}</select></label><label className="block text-sm">Evidencia y página<textarea className={input} rows={2} value={quote.evidence[c.id]||''} onChange={e=>update(quote.id,{evidence:{...quote.evidence,[c.id]:e.target.value}})}/></label></div>)}
      <label className="flex gap-2 text-sm font-semibold"><input type="checkbox" checked={quote.reviewed} onChange={e=>update(quote.id,{reviewed:e.target.checked})}/>He revisado los datos y la evidencia de esta oferta.</label><button className="text-sm text-red-700" onClick={()=>{setQuotes(q=>q.filter(v=>v.id!==quote.id));setDirty(true);}}>Quitar oferta de esta comparación</button></div></details>)}
      {plan.groups.map(group=>{const groupRows=rows.filter(r=>r.quote.groupId===group.id),best=groupRows.filter(r=>r.rank===1),pending=groupRows.some(r=>r.status==='pending');return <div key={group.id} className="space-y-2"><h3 className="font-semibold">{group.label}</h3><div className="overflow-x-auto"><table className="w-full text-sm border-collapse"><thead><tr>{['Proveedor','Precio Bs',...(plan.method==='calidad_precio'?['Precio / 50','Adicionales / 50','Total / 100']:[]),'Resultado'].map(h=><th key={h} className="border bg-white p-2 text-left">{h}</th>)}</tr></thead><tbody>{groupRows.map(r=><tr key={r.quote.id}><td className="border p-2">{r.quote.provider||'Sin nombre'}</td><td className="border p-2">{r.quote.price}</td>{plan.method==='calidad_precio'&&[r.pp,r.pra,r.total].map((n,i)=><td key={i} className="border p-2">{n===null?'—':n.toFixed(2)}</td>)}<td className="border p-2">{r.rank?`Posición ${r.rank}. `:''}{r.reason}</td></tr>)}</tbody></table></div><p className="text-sm">{!groupRows.length?'Todavía no hay ofertas para esta unidad.':pending?'Resultado provisional: hay ofertas por verificar.':best.length>1?'Hay empate. Se requiere una resolución documentada.':best.length===1?`Mejor resultado evaluado: ${best[0].quote.provider}. Requiere revisión del responsable.`:'No hay ofertas habilitadas.'}</p></div>})}
      <div className="flex gap-2 flex-wrap"><button className={`${button} bg-primary text-white`} disabled={!quotes.length||!!calculationError} onClick={save}>Guardar comparación</button><button className={button} disabled={!quotes.length||!!calculationError} onClick={download}>Descargar cuadro comparativo Word</button></div>
      {!!history.length&&<details className="text-sm"><summary className="cursor-pointer">Comparaciones anteriores ({history.length})</summary>{history.map((v,i)=><p key={i} className="mt-2">{new Date(v.updatedAt).toLocaleString('es-BO')} · {methodLabels[v.plan.method]} · {v.quotes.length} ofertas <button className="underline" onClick={()=>{const copy={plan:activePlan,quotes,updatedAt:new Date().toISOString()};setPlan(v.plan);setQuotes(v.quotes);setGroupId(v.plan.groups[0]?.id||'');setHistory(h=>h.map((x,j)=>j===i?copy:x));setDirty(true);}}>Abrir esta versión</button></p>)}</details>}
    </fieldset>
    {busy&&<p role="status" className="text-sm">Procesando cotización…</p>}{message&&<p role="status" className="text-sm">{message}</p>}{(error||calculationError)&&<p role="alert" className="text-sm text-red-800">{error||calculationError}</p>}
  </section>;
}
