'use client';
import { useEffect, useState } from 'react';
import type { Adquisicion, Carpeta } from '@/types';
import { DataStore } from '@/lib/store/dataStore';
import { initialBrief } from '@/lib/docx/purchaseBrief';
import { fixedModel, FixedDraft } from '@/lib/docx/fixedModels';
import { applySelection, assertPlan, awardLabels, AwardMode, initialSelection, maintenanceConditions, methodLabels, planFields, SelectionPlan } from '@/lib/procurement/selection';

const input='w-full rounded-lg border border-slate-300 bg-white p-2 text-sm';
const button='rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold disabled:opacity-50';
export function SelectionPanel({adquisicion,carpetas,onSaved,disabled=false}:{adquisicion:Adquisicion;carpetas:Carpeta[];onSaved:()=>void;disabled?:boolean}) {
  const recoveryKey=`selection-draft:${adquisicion.id}`;
  const [recovery]=useState(()=>{try{const saved=JSON.parse(localStorage.getItem(recoveryKey)||'null');return saved?.updatedAt>(Date.parse(adquisicion.selection_plan?.confirmedAt||'')||0)?saved:null;}catch{return null;}});
  const [plan,setPlan]=useState<SelectionPlan>(()=>recovery?.plan||initialSelection(adquisicion));
  const [open,setOpen]=useState(!adquisicion.selection_plan);
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(recovery?'Se recuperaron tus condiciones sin guardar.':''),[dirty,setDirty]=useState(!!recovery);
  useEffect(()=>{if(dirty)try{localStorage.setItem(recoveryKey,JSON.stringify({plan,updatedAt:Date.now()}));}catch{setError('No se pudo guardar la recuperación local. Guarda las condiciones antes de salir.');}},[plan,dirty,recoveryKey]);
  function change(updates:Partial<SelectionPlan>){setPlan(p=>({...p,...updates}));setDirty(true);setMessage('Cambios en condiciones sin guardar.');setError('');}
  function changeMode(mode:AwardMode){change({awardMode:mode,groups:mode==='item'?adquisicion.items.map(i=>({id:`item-${i.id}`,label:`Ítem ${i.item}: ${i.descripcion}`,itemIds:[i.id],itemLabels:[`Ítem ${i.item}: ${i.descripcion}`],referencePrice:i.precioTotalEstimado>0?String(i.precioTotalEstimado):''})):[{id:crypto.randomUUID(),label:`${awardLabels[mode]} 1`,itemIds:adquisicion.items.map(i=>i.id),itemLabels:adquisicion.items.map(i=>`Ítem ${i.item}: ${i.descripcion}`),referencePrice:adquisicion.prevision_presupuesto>0?String(adquisicion.prevision_presupuesto):''}]});}
  async function suggest(){setBusy(true);setError('');try{const form=new FormData();form.append('request',JSON.stringify({action:'suggest',plan,context:JSON.stringify({objeto:adquisicion.titulo_proceso,items:adquisicion.items,plazo:adquisicion.plazo_entrega_dias,finalidad:adquisicion.asistente_compra?.purpose})}));const res=await fetch('/api/evaluation',{method:'POST',body:form});const data=await res.json();if(!res.ok)throw Error(data.error);change(data);setMessage('La IA propuso criterios. Revisa los umbrales y ponderaciones antes de guardar.');}catch(e){setError(e instanceof Error?e.message:'No se pudo proponer criterios.');}finally{setBusy(false);}}
  async function save(){setBusy(true);setError('');try{
    const next={...plan,revision:crypto.randomUUID(),confirmedAt:new Date().toISOString()};assertPlan(next,next.method==='calidad_precio');
    const included=next.groups.flatMap(g=>g.itemIds);if(adquisicion.items.some(i=>!included.includes(i.id))||included.some(id=>!adquisicion.items.some(i=>i.id===id)))throw Error('Asigna cada ítem del expediente a una unidad de adjudicación.');
    const current=DataStore.getAdquisicionById(adquisicion.id)||adquisicion,brief=initialBrief(current);
    const revision=crypto.randomUUID(),prepared={...current.borradores_ia};
    for(const number of [1,2]){
      const model=fixedModel(number),latest=carpetas.find(c=>c.numero===number)?.documentos.filter(d=>d.metadata?.fixedDraft?.modelVersion===model.version).sort((a,b)=>b.fecha_creacion.localeCompare(a.fecha_creacion))[0];
      let draft:FixedDraft|undefined=prepared[number]?.draft;let time=Date.parse(prepared[number]?.updatedAt||'')||0;
      if(latest&&Date.parse(latest.fecha_creacion)>time){draft=latest.metadata!.fixedDraft;time=Date.parse(latest.fecha_creacion);}
      try{const recovery=JSON.parse(localStorage.getItem(`fixed-draft:${adquisicion.id}:${number}`)||'null');if(recovery?.draft?.modelVersion===model.version&&recovery.updatedAt>time)draft=recovery.draft;}catch{}
      if(draft)prepared[number]={draft:applySelection(draft,next,number),updatedAt:next.confirmedAt,briefRevision:revision};
    }
    const fields=planFields(next,1);
    const result=await DataStore.updateAdquisicion(adquisicion.id,{selection_plan:next,asistente_compra:{...brief,decisions:{...brief.decisions,...fields},revision},borradores_ia:prepared,
      metodo_seleccion:methodLabels[next.method],metodo_seleccion_texto:fields.seleccion,categoria_texto:next.categoryDescription,forma_adjudicacion:fields.adjudicacion,
      vigencia_propuesta_texto:fields.vigencia,forma_pago_texto:fields.pago,multas_texto:fields.multas});
    if(!result.success)throw Error(result.error);
    for(const n of [1,2])if(prepared[n])localStorage.removeItem(`fixed-draft:${adquisicion.id}:${n}`);
    const sync=await DataStore.flushPending();setDirty(false);localStorage.removeItem(recoveryKey);setPlan(next);setMessage(sync.success?'Condiciones guardadas en el TDR y S1. Al preparar las demás carpetas se usarán estas condiciones.':'Condiciones guardadas en este equipo; falta sincronizar con la nube.');onSaved();
  }catch(e){setError(e instanceof Error?e.message:'No se pudieron guardar las condiciones.');}finally{setBusy(false);}}
  return <section className="mb-5 rounded-xl border border-slate-300 bg-white p-4 space-y-3">
    <div className="flex justify-between items-center gap-3"><div><h2 className="font-bold text-lg text-primary">Condiciones y evaluación del TDR</h2><p className="text-sm text-slate-600">{adquisicion.selection_plan?`${methodLabels[adquisicion.selection_plan.method]} · Por ${awardLabels[adquisicion.selection_plan.awardMode]}`:'Elige el modelo y confirma las condiciones una sola vez.'}</p></div><button className={button} onClick={()=>setOpen(!open)}>{open?'Ocultar condiciones':'Revisar condiciones'}</button></div>
    {open&&<fieldset disabled={busy||disabled} className="space-y-4 min-w-0">
      <div className="grid sm:grid-cols-2 gap-3">
        <label className="text-sm font-semibold">Base del documento<select className={input} value={plan.profile} onChange={e=>{const maintenance=e.target.value==='mantenimiento_higiene';change({profile:maintenance?'mantenimiento_higiene':'general',categoryDescription:maintenance?'Servicios General / Mantenimiento e Higiene Industrial':adquisicion.categoria,conditions:maintenance?{...maintenanceConditions}:{vigencia:"",pago:"",multas:""}});}}><option value="general">General: condiciones propias de esta compra</option><option value="mantenimiento_higiene">Servicios de mantenimiento e higiene</option></select></label>
        <label className="text-sm font-semibold">Método de selección<select className={input} value={plan.method} onChange={e=>change({method:e.target.value as SelectionPlan['method']})}><option value="menor_precio">Menor precio</option><option value="calidad_precio">Calidad y Precio</option></select></label>
      </div>
      <p className="text-sm text-slate-600">{plan.method==='menor_precio'?'Se compara el precio de las ofertas que cumplen los requisitos mínimos.':'Se verifica el cumplimiento mínimo y se suman hasta 50 puntos por precio y 50 por requisitos adicionales, según el modelo aportado.'}</p>
      <label className="block text-sm">Especialidad / categoría descriptiva<input className={input} value={plan.categoryDescription} onChange={e=>change({categoryDescription:e.target.value})}/></label>
      <details className="text-sm"><summary className="cursor-pointer font-semibold">Vigencia, pago y multas</summary><div className="space-y-3 mt-3">{(['vigencia','pago','multas'] as const).map((key,i)=><label key={key} className="block">{['Vigencia de la propuesta','Forma de pago','Aplicación de multas'][i]}<textarea className={input} rows={key==='pago'?7:3} value={plan.conditions[key]||''} onChange={e=>change({conditions:{...plan.conditions,[key]:e.target.value}})}/></label>)}<p>Estas condiciones corresponden a la compra; no se presentan como una norma general.</p><label className="block">Categoría por cuantía para S1 (si está determinada)<input className={input} value={plan.amountCategory} onChange={e=>change({amountCategory:e.target.value})}/></label></div></details>
      <label className="block text-sm font-semibold">Forma de adjudicación<select className={input} value={plan.awardMode} onChange={e=>changeMode(e.target.value as AwardMode)}>{Object.entries(awardLabels).map(([key,label])=><option key={key} value={key}>Por {label}</option>)}</select></label>
      {!adquisicion.items.length&&<p className="text-sm text-amber-800">Primero incorpora los ítems con el asistente de la compra.</p>}
      {!!adquisicion.items.length&&<button className={`${button} text-xs`} onClick={()=>changeMode(plan.awardMode)}>Actualizar unidades desde los ítems de la compra</button>}
      {plan.groups.map((group,index)=><div key={group.id} className="rounded-lg border p-3 space-y-2"><div className="grid sm:grid-cols-2 gap-3"><label className="text-sm">Unidad de adjudicación<input className={input} value={group.label} onChange={e=>change({groups:plan.groups.map((g,i)=>i===index?{...g,label:e.target.value}:g)})}/></label><label className="text-sm">Previsión total de precio (Bs){plan.method==='calidad_precio'?' · requerida':''}<input className={input} inputMode="decimal" value={group.referencePrice} placeholder="Sin separadores de miles" onChange={e=>change({groups:plan.groups.map((g,i)=>i===index?{...g,referencePrice:e.target.value}:g)})}/></label></div>{plan.awardMode!=='item'&&<div className="text-sm space-y-1">{adquisicion.items.map(item=><label key={item.id} className="flex gap-2"><input type="checkbox" checked={group.itemIds.includes(item.id)} onChange={e=>{const ids=e.target.checked?[...group.itemIds,item.id]:group.itemIds.filter(id=>id!==item.id);change({groups:plan.groups.map((g,i)=>i===index?{...g,itemIds:ids,itemLabels:ids.map(id=>{const it=adquisicion.items.find(i=>i.id===id)!;return `Ítem ${it.item}: ${it.descripcion}`;})}:g)});}}/>Ítem {item.item}: {item.descripcion}</label>)}<button className="text-red-700" onClick={()=>change({groups:plan.groups.filter((_,i)=>i!==index)})}>Quitar unidad</button></div>}</div>)}
      {plan.awardMode!=='item'&&<button className={button} onClick={()=>change({groups:[...plan.groups,{id:crypto.randomUUID(),label:`${awardLabels[plan.awardMode]} ${plan.groups.length+1}`,itemIds:[],referencePrice:''}]})}>Añadir {awardLabels[plan.awardMode]}</button>}
      <details open={plan.method==='calidad_precio'} className="text-sm"><summary className="font-semibold cursor-pointer">Requisitos y criterios de evaluación</summary><div className="space-y-3 mt-3">{plan.method==='calidad_precio'&&<><button className={button} onClick={suggest}>Proponer criterios con IA</button><p>Revisa las propuestas antes de confirmar. Los mínimos excluyen; los adicionales otorgan puntos.</p></>}{plan.minimums.map((m,i)=><div key={m.id} className="flex gap-2"><label className="flex-1">Requisito mínimo {i+1}<textarea className={input} rows={2} value={m.label} onChange={e=>change({minimums:plan.minimums.map((v,j)=>i===j?{...v,label:e.target.value}:v)})}/></label><button onClick={()=>change({minimums:plan.minimums.filter((_,j)=>i!==j)})}>Quitar</button></div>)}<button className={button} onClick={()=>change({minimums:[...plan.minimums,{id:crypto.randomUUID(),label:''}]})}>Añadir mínimo</button>
      {plan.method==='calidad_precio'&&<>{plan.criteria.map((c,i)=><div key={c.id} className="border rounded-lg p-3 space-y-2"><div className="flex gap-2"><label className="flex-1">Criterio adicional<input className={input} value={c.label} onChange={e=>change({criteria:plan.criteria.map((v,j)=>i===j?{...v,label:e.target.value}:v)})}/></label><label className="w-24">Peso %<input type="number" min="1" max="100" className={input} value={c.weight} onChange={e=>change({criteria:plan.criteria.map((v,j)=>i===j?{...v,weight:Number(e.target.value)}:v)})}/></label></div>{c.levels.map((l,n)=><div key={l.id} className="flex gap-2"><label className="flex-1">Condición del nivel<input className={input} value={l.label} onChange={e=>change({criteria:plan.criteria.map((v,j)=>i===j?{...v,levels:v.levels.map((x,k)=>k===n?{...x,label:e.target.value}:x)}:v)})}/></label><label className="w-24">Puntos<input className={input} type="number" min="0" max="100" value={l.score} onChange={e=>change({criteria:plan.criteria.map((v,j)=>i===j?{...v,levels:v.levels.map((x,k)=>k===n?{...x,score:Number(e.target.value)}:x)}:v)})}/></label><button disabled={c.levels.length<=2} onClick={()=>change({criteria:plan.criteria.map((v,j)=>i===j?{...v,levels:v.levels.filter((_,k)=>k!==n)}:v)})}>Quitar nivel</button></div>)}<button className={button} disabled={c.levels.length>=8} onClick={()=>change({criteria:plan.criteria.map((v,j)=>i===j?{...v,levels:[...v.levels,{id:crypto.randomUUID(),label:"",score:50}]}:v)})}>Añadir nivel</button> <button className="text-red-700" onClick={()=>change({criteria:plan.criteria.filter((_,j)=>j!==i)})}>Quitar criterio</button></div>)}<button className={button} onClick={()=>change({criteria:[...plan.criteria,{id:crypto.randomUUID(),label:'',weight:0,levels:[{id:'minimum',label:'',score:0},{id:'excellent',label:'',score:100}]}]})}>Añadir criterio</button><p className="font-semibold">Ponderación total: {plan.criteria.reduce((sum,c)=>sum+c.weight,0)} % de 100 %</p></>}
      </div></details>
      <button className={`${button} bg-primary text-white`} onClick={save}>Guardar condiciones y actualizar documentos</button>
      <p className="text-xs text-slate-600">Las evaluaciones ya guardadas conservan su versión de reglas. Los criterios se confirman antes de comparar cotizaciones.</p>
    </fieldset>}
    {busy&&<p role="status" className="text-sm">Preparando condiciones…</p>}{message&&<p role="status" className="text-sm text-primary">{message}</p>}{error&&<p role="alert" className="text-sm text-red-800">{error}</p>}
  </section>;
}
