"use client";
import React, { useState } from "react";
import Link from "next/link";
import { Topbar } from "@/components/layout/Topbar";

export default function LibraryPage() {
  const [status,setStatus]=useState<{connected:boolean;previewConfigured:boolean;writingConfigured:boolean;company:string}|null>(null);
  const [busy,setBusy]=useState(false),[error,setError]=useState('');
  async function check(){setBusy(true);setError('');try{const res=await fetch('/api/knowledge-status');if(!res.ok)throw Error('No se pudo consultar la conexión.');setStatus(await res.json());}catch{setError('No se pudo consultar la conexión. Intenta de nuevo.');}finally{setBusy(false);}}
  return <><Topbar title="Biblioteca y revisión"/><main className="flex-1 overflow-y-auto p-6"><div className="mx-auto max-w-3xl space-y-6 text-base"><h1 className="text-2xl font-bold text-primary">Biblioteca de ENDE Deoruro</h1><p>Los reglamentos y manuales se mantienen en AnythingLLM. Al completar un documento, el sistema consulta la biblioteca asignada a esta empresa y OpenCode GO redacta el borrador.</p><div className="rounded-xl bg-white border p-5 space-y-3"><h2 className="font-semibold">Organización de las fuentes</h2><p>Guarda cada empresa en un espacio separado. Identifica los manuales con empresa, título, versión y vigencia. Revisa las versiones sustituidas antes de incorporar una actualización.</p><p>Los antecedentes de una compra se adjuntan dentro de su expediente. No se incorporan automáticamente como normas.</p><p className="text-sm text-slate-600">Esta aplicación tiene habilitados los modelos y la biblioteca de ENDE. Antes de habilitar otra empresa se deben configurar sus modelos, biblioteca y permisos de acceso.</p></div><div className="rounded-xl bg-white border p-5 space-y-3"><h2 className="font-semibold">Comprobar servicios</h2><button disabled={busy} onClick={check} className="bg-primary text-white rounded-lg px-4 py-2 disabled:opacity-50">{busy?'Comprobando…':'Comprobar conexión'}</button>{error&&<p role="alert">{error}</p>}{status&&<ul className="list-disc pl-5 space-y-2"><li>Biblioteca: {status.connected?'conectada':'no disponible o espacio sin configurar'}</li><li>Credencial de redacción: {status.writingConfigured?'configurada (falta probar una generación)':'pendiente de configurar'}</li><li>Vista PDF: {status.previewConfigured?'configurada (falta comprobar conversión)':'pendiente; se ofrece lectura de contenido y Word'}</li></ul>}</div><div className="flex gap-5"><Link href="/plantillas" className="text-primary underline">Ver modelos Word</Link><Link href="/auditoria" className="text-primary underline">Consultar auditoría</Link><Link href="/" className="text-primary underline">Mis compras</Link></div></div></main></>;
}
