const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),Module=require('module'),ts=require('typescript');
require.extensions['.ts']=(m,file)=>m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,file);
const resolve=Module._resolveFilename;Module._resolveFilename=function(name,...args){return resolve.call(this,name.startsWith('@/')?path.join(process.cwd(),'src',name.slice(2)):name,...args)};
let aiReply={};const load=Module._load;Module._load=function(name,...args){if(name.endsWith('/ai/openCodeClient'))return{extractJsonFromText:JSON.parse,callOpenCodeGo:async(messages)=>JSON.stringify(messages[0].content.includes("EXTRACT_DOCUMENT_EVIDENCE")?{facts:[],missing:[],conflicts:[]}:aiReply)};if(name.endsWith('/ai/anythingLlmClient'))return{AnythingLlmClient:{searchWorkspaceSources:async()=>({sources:[]})}};return load.call(this,name,...args);};
const {initialSelection,planProblems,maintenanceConditions,evaluateQuotes,applySelection}=require('../src/lib/procurement/selection.ts');
const {seedFixedDraft,renderFixedWord,completeFixedDocument}=require('../src/lib/server/fixedDocuments.ts');
const {readQuote}=require('../src/lib/server/quoteAssistant.ts');
const {evaluationReport}=require('../src/lib/server/evaluationReport.ts');
const mammoth=require('mammoth');
const adq={id:'selection-test',codigo:'PRUEBA',empresa_id:'ende',titulo_proceso:'Servicio de limpieza y mantenimiento industrial',categoria:'Servicios',responsable_proceso:'Solicitante de prueba',unidad_solicitante:'Servicios',lugar_entrega:'Oruro',plazo_entrega_dias:30,prevision_presupuesto:10000,items:[{id:'one',item:1,descripcion:'Servicio de limpieza industrial',unidad:'Servicio',cantidad:1,precioTotalEstimado:10000,precioUnitarioEstimado:10000,especificacionMinima:'Limpieza de instalaciones según alcance confirmado.'}]};
const plan={...initialSelection(adq),method:'calidad_precio',revision:'reglas-prueba',confirmedAt:'2026-09-20T12:00:00.000Z',criteria:[{id:'quality',label:'Mejora acreditada sobre el mínimo definido',weight:100,levels:[{id:'min',label:'Cumple únicamente el mínimo',score:0},{id:'mid',label:'Cumple la mejora intermedia definida',score:50},{id:'max',label:'Cumple la mejora máxima definida',score:100}]}]};
const quote=(id,price,level='max')=>({id,provider:`Proveedor ${id}`,groupId:'one',price:String(price),source:'Cotización ficticia',reviewed:true,minimums:{'min-tecnico':'yes'},levels:{quality:level},evidence:{'min-tecnico':'Oferta, página 2: cumple el alcance completo.',quality:'Oferta, página 3: mejora acreditada.',precio:`Oferta: Bs ${price}, impuestos incluidos.`}});
(async()=>{
 assert.equal(initialSelection(adq).profile,'mantenimiento_higiene');assert.equal(initialSelection({...adq,categoria:'Bienes'}).profile,'general');assert.equal(initialSelection({...adq,titulo_proceso:'Servicio de auditoría'}).profile,'general');
 assert.deepEqual(planProblems(plan,true),[]);
 for(const [price,expected] of [[7999.99,50],[8000,50],[8000.01,50],[10000,25],[12000,0]])assert.equal(evaluateQuotes(plan,[quote('a',price)])[0].pp,expected);
 assert.equal(evaluateQuotes(plan,[quote('a',12000.01)])[0].status,'excluded');
 assert.equal(evaluateQuotes(plan,[{...quote('a',9000),reviewed:false}])[0].status,'pending');
 assert.equal(evaluateQuotes(plan,[{...quote('a',9000),minimums:{'min-tecnico':'no'}}])[0].status,'excluded');
 assert.equal(evaluateQuotes(plan,[{...quote('a',9000),minimums:{'min-tecnico':'no'},evidence:{}}])[0].status,'pending');
 assert.equal(evaluateQuotes(plan,[{...quote('a',9000),evidence:{}}])[0].status,'pending');
 assert.equal(evaluateQuotes(plan,[{...quote('a',9000),levels:{}}])[0].status,'pending');
 assert.equal(evaluateQuotes(plan,[quote('a','0')])[0].status,'pending');
 assert.equal(evaluateQuotes(plan,[quote('a','9,000.00')])[0].status,'pending');
 const tie=evaluateQuotes(plan,[quote('a',9000),quote('b',9000)]);assert.deepEqual(tie.map(r=>r.rank),[1,1]);
 const minimum=evaluateQuotes({...plan,method:'menor_precio'},[quote('a',8000,'min'),quote('b',9000)]);assert.equal(minimum[0].rank,1);assert.equal(minimum[1].rank,2);
 const quality=evaluateQuotes(plan,[quote('a',8000,'min'),quote('b',9000)]);assert.equal(quality[1].rank,1);assert.equal(quality[1].total,87.5);
 const groups={...plan,groups:[...plan.groups,{id:'two',label:'Ítem 2',itemIds:['two'],referencePrice:'5000'}]};assert.deepEqual(evaluateQuotes(groups,[quote('a',9000),{...quote('b',4000),groupId:'two'}]).map(r=>r.rank),[1,1]);
 assert.ok(planProblems({...plan,criteria:[{...plan.criteria[0],weight:80}]}).length);assert.ok(planProblems({...plan,priceWeight:60}).length);assert.ok(planProblems({...plan,groups:[{...plan.groups[0],referencePrice:'0'}]},true).length);assert.ok(planProblems({...plan,criteria:[]}).length);assert.ok(planProblems({...plan,groups:[...plan.groups,{...plan.groups[0],id:'duplicate'}]}).length);
 const legacy=seedFixedDraft(1,adq);assert.equal(legacy.selectionPlan,undefined);
 adq.selection_plan=plan;
 const draft=seedFixedDraft(1,adq);assert.equal(draft.fields.multas,maintenanceConditions.multas);assert.match(draft.fields.seleccion,/Calidad y Precio/);assert.match(draft.fields.vigencia,/30 días/);assert.match(draft.fields.categoria,/Mantenimiento/);assert.equal(draft.selectionPlan.revision,plan.revision);
 const s1=seedFixedDraft(2,adq);assert.equal(s1.fields.seleccion,'Calidad y Precio');assert.notEqual(s1.fields.categoria,plan.categoryDescription);
 const cleared=applySelection(draft,{...plan,profile:'general',conditions:{vigencia:'',pago:'',multas:''}},1);assert.equal(cleared.fields.pago,'[PENDIENTE]');assert.ok(!cleared.confirmedFields.includes('pago'));
 aiReply={fields:{...draft.fields,seleccion:'Menor precio',multas:'[PENDIENTE]',categoria:'[PENDIENTE]'},items:draft.items};const completed=await completeFixedDocument(1,adq,draft,'');assert.equal(completed.fields.multas,maintenanceConditions.multas);assert.match(completed.fields.seleccion,/Calidad y Precio/);assert.equal(completed.selectionPlan.revision,plan.revision);
 const before=JSON.stringify(draft.selectionPlan);adq.selection_plan={...plan,method:'menor_precio'};assert.equal(JSON.stringify(draft.selectionPlan),before,'La versión del documento debe conservarse');
 const dir='test-results/selection';fs.mkdirSync(dir,{recursive:true});
 for(const [name,input] of [['calidad-precio',draft],['menor-precio',applySelection(draft,{...plan,method:'menor_precio'},1)],['legacy',legacy]]){const {buffer}=await renderFixedWord(1,input);fs.writeFileSync(`${dir}/${name}.docx`,buffer);const txt=(await mammoth.extractRawText({buffer})).value;if(name==='calidad-precio'){assert.match(txt,/3.3. MÉTODO DE EVALUACIÓN/);assert.match(txt,/PP = 50/);assert.match(txt,/Mejora acreditada/);assert.match(txt,/0.25%/);assert.ok(txt.indexOf('3.3. MÉTODO')>txt.indexOf('CARACTERÍSTICAS TÉCNICAS REQUERIDAS'));assert.ok(txt.indexOf('3.3. MÉTODO')<txt.lastIndexOf('4.   CALIDAD'));}else assert.ok(!txt.includes('3.3. MÉTODO DE EVALUACIÓN'));fs.writeFileSync(`${dir}/${name}.txt`,txt);}
 aiReply={provider:'Empresa extraída',price:'9000',minimums:{'min-tecnico':'yes'},levels:{quality:'max'},evidence:{}};let read=await readQuote(plan,'one','Cotización',[]);assert.equal(read.reviewed,false);assert.equal(read.minimums['min-tecnico'],'unknown');assert.equal(read.levels.quality,'');
 aiReply.evidence={'min-tecnico':'Cita del alcance',quality:'Cita de la mejora'};read=await readQuote(plan,'one','Cotización',[]);assert.equal(read.minimums['min-tecnico'],'yes');assert.equal(read.levels.quality,'max');assert.equal(read.reviewed,false);
 const report=await evaluationReport(adq.titulo_proceso,{plan,quotes:[quote('a',8000,'min'),quote('b',9000)],updatedAt:new Date().toISOString()});fs.writeFileSync(`${dir}/comparativo.docx`,report);assert.match((await mammoth.extractRawText({buffer:report})).value,/87.50/);
 fs.writeFileSync(`${dir}/fixture.json`,JSON.stringify({...adq,selection_plan:plan,quote_evaluation:{plan,quotes:[quote('a',8000,'min'),quote('b',9000)],updatedAt:new Date().toISOString()}},null,2));
 console.log('PASS condiciones por especialidad, mínimos, límites 80/120%, ponderaciones, empates, unidades separadas, lectura sin evidencia, reglas conservadas, ambos Word y cuadro comparativo.');
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
